### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by stynan27** [stynan27/BlockHeads#2]
### User Story
As a BlockHeads user,
I want a landing page for new users,
so that there is an initial place to navigate to our app that describes our product.

### Acceptance Criteria
- [ ] Done when a webpage exists to display on the initial landing of the BlockHeads app.
- [ ] Done when the webpage has a welcome title.
- [ ] Done when the webpage has a description of our product.
- [ ] Done when has a top-level toolbar/navigation element that carries between pages.
- [ ] Done when has a top-level footer element that carries between pages.
- [ ] Done when the footer has: contact info, and relevant links (github, linkedIn).

**Comment by stynan27** [comment]
- [ ] @jtangelo98 to mockup Social Links similar to:

![image](https://github.com/stynan27/BlockHeads/assets/32597881/8baaec60-75a2-46a5-9bb0-83f3c48a5dcb)

Idea is to have a button that links to our GitHub page (github icon) as well as separate icons for each of our linkedIn profiles.

Can be done with icon button for

**Comment by stynan27** [comment]
### TODOS
- [ ] Where to arrange linkedIn links?
- [ ] Github to the right in footer with company trademark/LLC? Or Github icon at the top left of the Title
- [ ] Background image/slideshow/carousel for content body?
- [ ] Example individual links to pages in navbar
