### ISSUE TITLE
Design layout of welcome page

### ISSUE THREAD

**Issue by stynan27** [stynan27/BlockHeads#3]
### Description
Create a Figma UX mockup of our welcome page so we have a design to implement.

Subtask of #2

**Comment by stynan27** [comment]
Blocked by: #6

**Comment by stynan27** [comment]
### Example footers
![image](https://github.com/stynan27/BlockHeads/assets/32597881/60106d74-dd20-48e3-81d0-810c666afcc1)
![image](https://github.com/stynan27/BlockHeads/assets/32597881/e82cb2b0-4670-4bcc-b4cf-8eab1bd93f78)

**Comment by stynan27** [comment]
### TODOS
- [ ] Where to arrange linkedIn links?
- [ ] Github to the right in footer with company trademark/LLC? Or Github icon at the top left of the Title
- [ ] Background image/slideshow/carousel for content body?
- [ ] Example individual links to pages in navbar

**Comment by stynan27** [comment]
- [ ] @jtangelo98 to mockup Social Links similar to:

![image](https://github.com/stynan27/BlockHeads/assets/32597881/8baaec60-75a2-46a5-9bb0-83f3c48a5dcb)

Idea is to have a button that links to our GitHub page (github icon) as well as separate icons for each of our linkedIn profiles.

Can be done with icon button for
