### ISSUE TITLE
Lego Set Management Page

### ISSUE THREAD

**Issue by stynan27** [stynan27/BlockHeads#9]
### User Story
As a BlockHeads user,
I want a page to create, read, & delete Lego sets,
so that I can manage my Lego sets

### Acceptance Criteria
- [ ] Done when a webpage exists to display a Table of Lego sets.
- [ ] Done when the Welcome page routes to this new Set management page.
- [ ] Done when this new set management page has a title "Set Management Page".
- [ ] Done when this new page has a table to list managed Lego sets.
- [ ] Done when we have a backend application to service client Lego set create, read, update, & delete requests.
- [ ] Done when a client can create a new Lego set with fields for: Set name, Number of parts, list of minifigure names, & PDF/image instructions.
- [ ] Done when a client can delete a set from the table of Lego sets.
- [ ] Done when a client can update a set from the table of Lego sets.
- [ ] Done when a client can return to the manage sets page and view previously created/altered/edited list of sets after server shutdown (persistence layer).

**Comment by stynan27** [comment]
We decided that set updates are out of scope for this sprint. Will revisit in a future separate issue/story.

**Comment by stynan27** [comment]
Since there is a lot of functionality here would be a good idea to at least have some unit tests per controller endpoint and new react UI additions.

### TODO ###
- [ ] Create unit tests for UI based on AC's above
- [ ] Create unit tests for API based on AC's above
